// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POC_TMB.Data;

#nullable disable

namespace POC_TMB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250909221217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("POC_TMB.Models.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a7b6f5c-0e3d-4c1b-9d7a-1b2c3d4e5f6a"),
                            Cliente = "Matheus Siqueira",
                            DataCriacao = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Produto = "Teste Tmb",
                            Status = "Pendente",
                            Valor = 1000m
                        },
                        new
                        {
                            Id = new Guid("f4a3e2d1-c0b9-4a8e-9d6c-5b4a3c2d1e0f"),
                            Cliente = "Julia Gomyde",
                            DataCriacao = new DateTime(2024, 1, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Produto = "Teste Tmb",
                            Status = "Concluido",
                            Valor = 1500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
